defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 2137
      consider_magic_clip: true
    direction: maximize
    study_name: minigrid
    storage: null
    # Variable n_trials decides how many times the algorithm
    # will be run to find the best set of hyperparamters
    n_trials: 10
    n_jobs: 1
    # Define below which parameters you want to tune
    params:
      pso.smin: range(-6.0, 0.0, 0.5)
      pso.smax: range(0.0, 6.0, 0.5)
      pso.phi1: range(0.0, 4.0, 0.5)
      pso.phi2: range(0.0, 4.0, 0.5)
      pso.w_dec: range(0.0020, 0.0050, 0.0005)


train:
  num_runs: 1
  multiprocessing: True

nn:
  input_size: 20
  hidden_size: 10
  output_size: 5

evolve:
  cross_prob: 0.5
  mutation_prob: 0.2
  lambda_coeff: 3
  selection_pressure: 3
  sigma_mutation: 1
  indpb_mutation: 0.5
  eta_crossover: 0.2
  selection_strategy: "comma" # Can be either "comma" or "plus"

island:
  pop_size : 50
  num_gens : 30
  num_islands : 4
  migration_interval : 25
  migration_size : 5

pso:
    pop_size: 100
    num_gens: 30
    smin: -3
    smax: 3
    phi1: 2.0
    phi2: 2.0
    w_dec: 0.0035

