train:
  pop_size: 100
  num_gens: 15

nn:
  input_size: 20
  hidden_size: 10
  output_size: 5

evolve:
  cross_prob: 0.5
  mutation_prob: 0.2
  lambda_coeff: 3
  selection_pressure: 3
  selection_strategy: "comma" # Can be either "comma" or "plus"
