defaults:
  - override hydra/sweeper: optuna
  - override hydra/sweeper/sampler: tpe

hydra:
  sweeper:
    sampler:
      seed: 2137
      consider_magic_clip: true
    direction: maximize
    study_name: minigrid
    storage: null
    # Variable n_trials decides how many times the algorithm
    # will be run to find the best set of hyperparamters
    n_trials: 10
    n_jobs: 1
    # Define below which parameters you want to tune
    params:
      evolve.mutation_prob: range(0.1, 0.3, 0.1)
      evolve.selection_strategy: choice("comma", "plus")

train:
  num_runs: 1
  pop_size: 100
  num_gens: 3
  multiprocessing: True

nn:
  input_size: 20
  hidden_size: 10
  output_size: 5

evolve:
  cross_prob: 0.5
  mutation_prob: 0.2
  lambda_coeff: 3
  selection_pressure: 3
  sigma_mutation: 1
  indpb_mutation: 0.5
  eta_crossover: 0.2
  selection_strategy: "plus" # Can be either "comma" or "plus"

